#############################################################################
# Makefile for building: SQDPF
# Generated by qmake (2.01a) (Qt 4.5.2) on: Wed May 26 15:24:24 2010
# Project:  SQDPF.pro
# Template: app
# Command: /opt/qt-embedded-linux-opensource-src-4.5.2/bin/qmake -spec /opt/Qtopia/mkspecs/qws/linux-arm-g++ -unix CONFIG+=debug -o Makefile SQDPF.pro
#############################################################################

####### Compiler, tools and options

CC            = armv5te-softfloat-linux-gcc
CXX           = armv5te-softfloat-linux-g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/Qtopia/mkspecs/qws/linux-arm-g++ -I. -I/opt/Qtopia/include/QtCore -I/opt/Qtopia/include/QtNetwork -I/opt/Qtopia/include/QtGui -I/opt/Qtopia/include/QtWebKit -I/opt/Qtopia/include -I. -I.
LINK          = armv5te-softfloat-linux-g++
LFLAGS        = -Wl,-rpath,/opt/QTE/lib
LIBS          = $(SUBLIBS)  -L/opt/Qtopia/lib -lQtWebKit -L/opt/lib/socle-tslib/lib -L/opt/FriendlyARM/socle/common-tst/lib -L/opt/Qtopia/lib -lQtGui -lts -lQtNetwork -lQtCore -lm -lrt -ldl -lpthread
AR            = armv5te-softfloat-linux-ar cqs
RANLIB        = 
QMAKE         = /opt/qt-embedded-linux-opensource-src-4.5.2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		charThread.cpp \
		WidgetKeyboard.cpp moc_mainwindow.cpp \
		moc_WidgetKeyboard.cpp \
		qrc_res.cpp
OBJECTS       = main.o \
		mainwindow.o \
		charThread.o \
		WidgetKeyboard.o \
		moc_mainwindow.o \
		moc_WidgetKeyboard.o \
		qrc_res.o
DIST          = /opt/Qtopia/mkspecs/common/g++.conf \
		/opt/Qtopia/mkspecs/common/unix.conf \
		/opt/Qtopia/mkspecs/common/linux.conf \
		/opt/Qtopia/mkspecs/common/qws.conf \
		/opt/Qtopia/mkspecs/qconfig.pri \
		/opt/Qtopia/mkspecs/features/qt_functions.prf \
		/opt/Qtopia/mkspecs/features/qt_config.prf \
		/opt/Qtopia/mkspecs/features/exclusive_builds.prf \
		/opt/Qtopia/mkspecs/features/default_pre.prf \
		/opt/Qtopia/mkspecs/features/debug.prf \
		/opt/Qtopia/mkspecs/features/default_post.prf \
		/opt/Qtopia/mkspecs/features/warn_on.prf \
		/opt/Qtopia/mkspecs/features/qt.prf \
		/opt/Qtopia/mkspecs/features/unix/thread.prf \
		/opt/Qtopia/mkspecs/features/moc.prf \
		/opt/Qtopia/mkspecs/features/resources.prf \
		/opt/Qtopia/mkspecs/features/uic.prf \
		/opt/Qtopia/mkspecs/features/yacc.prf \
		/opt/Qtopia/mkspecs/features/lex.prf \
		/opt/Qtopia/mkspecs/features/include_source_dir.prf \
		SQDPF.pro
QMAKE_TARGET  = SQDPF
DESTDIR       = 
TARGET        = SQDPF

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_WidgetKeyboard.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SQDPF.pro  /opt/Qtopia/mkspecs/qws/linux-arm-g++/qmake.conf /opt/Qtopia/mkspecs/common/g++.conf \
		/opt/Qtopia/mkspecs/common/unix.conf \
		/opt/Qtopia/mkspecs/common/linux.conf \
		/opt/Qtopia/mkspecs/common/qws.conf \
		/opt/Qtopia/mkspecs/qconfig.pri \
		/opt/Qtopia/mkspecs/features/qt_functions.prf \
		/opt/Qtopia/mkspecs/features/qt_config.prf \
		/opt/Qtopia/mkspecs/features/exclusive_builds.prf \
		/opt/Qtopia/mkspecs/features/default_pre.prf \
		/opt/Qtopia/mkspecs/features/debug.prf \
		/opt/Qtopia/mkspecs/features/default_post.prf \
		/opt/Qtopia/mkspecs/features/warn_on.prf \
		/opt/Qtopia/mkspecs/features/qt.prf \
		/opt/Qtopia/mkspecs/features/unix/thread.prf \
		/opt/Qtopia/mkspecs/features/moc.prf \
		/opt/Qtopia/mkspecs/features/resources.prf \
		/opt/Qtopia/mkspecs/features/uic.prf \
		/opt/Qtopia/mkspecs/features/yacc.prf \
		/opt/Qtopia/mkspecs/features/lex.prf \
		/opt/Qtopia/mkspecs/features/include_source_dir.prf \
		/opt/Qtopia/lib/libQtWebKit.prl \
		/opt/Qtopia/lib/libQtGui.prl \
		/opt/Qtopia/lib/libQtNetwork.prl \
		/opt/Qtopia/lib/libQtCore.prl
	$(QMAKE) -spec /opt/Qtopia/mkspecs/qws/linux-arm-g++ -unix CONFIG+=debug -o Makefile SQDPF.pro
/opt/Qtopia/mkspecs/common/g++.conf:
/opt/Qtopia/mkspecs/common/unix.conf:
/opt/Qtopia/mkspecs/common/linux.conf:
/opt/Qtopia/mkspecs/common/qws.conf:
/opt/Qtopia/mkspecs/qconfig.pri:
/opt/Qtopia/mkspecs/features/qt_functions.prf:
/opt/Qtopia/mkspecs/features/qt_config.prf:
/opt/Qtopia/mkspecs/features/exclusive_builds.prf:
/opt/Qtopia/mkspecs/features/default_pre.prf:
/opt/Qtopia/mkspecs/features/debug.prf:
/opt/Qtopia/mkspecs/features/default_post.prf:
/opt/Qtopia/mkspecs/features/warn_on.prf:
/opt/Qtopia/mkspecs/features/qt.prf:
/opt/Qtopia/mkspecs/features/unix/thread.prf:
/opt/Qtopia/mkspecs/features/moc.prf:
/opt/Qtopia/mkspecs/features/resources.prf:
/opt/Qtopia/mkspecs/features/uic.prf:
/opt/Qtopia/mkspecs/features/yacc.prf:
/opt/Qtopia/mkspecs/features/lex.prf:
/opt/Qtopia/mkspecs/features/include_source_dir.prf:
/opt/Qtopia/lib/libQtWebKit.prl:
/opt/Qtopia/lib/libQtGui.prl:
/opt/Qtopia/lib/libQtNetwork.prl:
/opt/Qtopia/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/Qtopia/mkspecs/qws/linux-arm-g++ -unix CONFIG+=debug -o Makefile SQDPF.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SQDPF1.0.0 || $(MKDIR) .tmp/SQDPF1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SQDPF1.0.0/ && $(COPY_FILE) --parents mainwindow.h charThread.h WidgetKeyboard.h .tmp/SQDPF1.0.0/ && $(COPY_FILE) --parents res.qrc .tmp/SQDPF1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp charThread.cpp WidgetKeyboard.cpp .tmp/SQDPF1.0.0/ && $(COPY_FILE) --parents mainwindow.ui WidgetKeyboard.ui .tmp/SQDPF1.0.0/ && (cd `dirname .tmp/SQDPF1.0.0` && $(TAR) SQDPF1.0.0.tar SQDPF1.0.0 && $(COMPRESS) SQDPF1.0.0.tar) && $(MOVE) `dirname .tmp/SQDPF1.0.0`/SQDPF1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SQDPF1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_WidgetKeyboard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_WidgetKeyboard.cpp
moc_mainwindow.cpp: charThread.h \
		WidgetKeyboard.h \
		ui_WidgetKeyboard.h \
		mainwindow.h
	/opt/Qtopia/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_WidgetKeyboard.cpp: ui_WidgetKeyboard.h \
		WidgetKeyboard.h
	/opt/Qtopia/bin/moc $(DEFINES) $(INCPATH) WidgetKeyboard.h -o moc_WidgetKeyboard.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		media-playback-pause.png \
		zoom-fit-page.png \
		go-previous.png \
		lincity-ng.png \
		zoom-in.png \
		zoom-out.png \
		media-seek-forward2.png \
		go-next.png \
		edit-undo.png \
		zoom-fit-width.png \
		media-seek-forward1.png \
		go-first.png \
		media-playback-stop.png \
		go-last.png \
		gkdebconf.png \
		dates.png \
		mplayer.png \
		audacious.png \
		web-browser.png \
		network-wireless.png \
		f-spot.png \
		clock.png
	/opt/Qtopia/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_WidgetKeyboard.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_WidgetKeyboard.h
ui_mainwindow.h: mainwindow.ui
	/opt/Qtopia/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_WidgetKeyboard.h: WidgetKeyboard.ui
	/opt/Qtopia/bin/uic WidgetKeyboard.ui -o ui_WidgetKeyboard.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		charThread.h \
		WidgetKeyboard.h \
		ui_WidgetKeyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		charThread.h \
		WidgetKeyboard.h \
		ui_WidgetKeyboard.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

charThread.o: charThread.cpp charThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o charThread.o charThread.cpp

WidgetKeyboard.o: WidgetKeyboard.cpp WidgetKeyboard.h \
		ui_WidgetKeyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WidgetKeyboard.o WidgetKeyboard.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_WidgetKeyboard.o: moc_WidgetKeyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WidgetKeyboard.o moc_WidgetKeyboard.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

